### ISSUE TITLE
Short-circuit downloadDelay

### ISSUE THREAD

**Issue by lorensr** [jamielob/reloader#1]
https://github.com/jamielob/reloader/blob/master/packages/reloader/reloader.js#L42-L63

Timer should be worst-case – can also have an `autorun` that does it immediately on `updateAvailable` true

**Comment by jamielob** [comment]
@lorensr: Can't do that without a better API. If we update automatically at that point, and there is a newer HCP waiting, it will take multiple starts of the app to get it up to date.

**Comment by lorensr** [comment]
I see. I was thinking about my only-post-install scenario. 

In the general case, to avoid the situation you mention, you could do it only when it's not initially available:

``` coffeescript
if updateAvailable
  # check for even newer update
  setTimeout ->
    if updateAvailable
      update()
    else
      release()
  , downloadDelay
else
  # wait until available or give up on timeout 
  Tracker.autorun (c) ->
    if updateAvailable
      update()

    setTimeout ->
      c.stop()
      release()
    , downloadDelay
```

**Comment by jamielob** [comment]
@lorensr - Playing with possible ways to do this with options.  I've added a section to the Readme outlining possible `refresh` and `check` options.  Can you think of any scenarios that a combination of these wouldn't cover?

https://github.com/jamielob/reloader/tree/master/packages/reloader#possible-refresh-modes

**Comment by lorensr** [comment]
Looks good! Not clear from check section what happens during checking (launchscreen up)

**Comment by jamielob** [comment]
Very good point!

**Comment by jamielob** [comment]
@lorensr - I've refactored the package and simplified the options.  I believe that I still cover all of the use cases we discussed.  Your main case would simply be covered by setting `Reloader.check = 'firstStart'`. 

Here's the new readme:
https://github.com/jamielob/reloader/tree/master/packages/reloader

Mind giving it a spin?

**Comment by lorensr** [comment]
Thanks! I will once I switch to 1.3 :) few notes now tho:
- usually the repo on a package has the package at the repo base, and the test app is a separate repo
- usually i see two spaces instead of tabs 😜
- usually pkg config is done like 

```
Reloader.configure({
  check: 'firstStart',
  checkTimer: 6000
})
```

**Comment by jamielob** [comment]
- This is in the works.
- You're just nitpicking.  I'm going to start mixing tabs and spaces to really piss you off.
- Yup I'll change to that.

**Comment by jamielob** [comment]
Items 1 and 3 taken care of and you're not getting 2 ;)

**Comment by lorensr** [comment]
Yay!

Now see if I was nitpicking I would say who doesn't have spaces after // ?! 😜

**Comment by jamielob** [comment]
//AllTheRageInEurope

**Comment by lorensr** [comment]
Oh, I guess that's okay then. Europeans are supposed to be cultured.

**Comment by lorensr** [comment]
Alright, I figured out the right lisp to get my editor to switch to tabs.
Just for you 😊

**Comment by jamielob** [comment]
Haha. did you see this commit:
https://github.com/jamielob/reloader/commit/e511abe85058a3c3a70debfc09dd0a4473924343
