### ISSUE TITLE
Possible configurations

### ISSUE THREAD

**Issue by jamielob** [jamielob/reloader#6]
**Working blueprint**

When to do additional checks:
- Do an additional check on first start (default)
- Do additional checks on every start
- Never do an additional check

When to reload the code already downloaded:
- Only on starts (default)
- Starts plus resume
- Instantly

How to differentiate between a start and a resume:
- System resume event and an idle timer (default) 
- Just the system resume event
- Just an idle timer

**Comment by jamielob** [comment]
Default:

```
Reloader.configure({
  check: false,
  reload: 'start',
  resumeMethod: 'eventAndTimer',
  resumeTimer: 1000 * 60 * 60, // 1 hour
  launchScreenDelay: 100,
});
```
- Never perform additional checks, therefore no additional delays
- Only reload to the last downloaded code on an app start
- Determine a start from a resume using the system event and a timer  (**Perhaps this should be just the timer by default? More conservative, especially for larger apps**)
- Expire the resume after an hour
- Hold the launchscreen for 100ms to hide the white flash

**Comment by lorensr** [comment]
For `reload: start`, we're never calling `.reload()`, so we don't need `resumeMethod/Timer`, right? I'm fine w/ rest, let's just strongly recommend at least check first start :)

**Comment by jamielob** [comment]
I think we do - because if the `resumeTimer` runs out then it would be considered a start next time.

**Comment by jamielob** [comment]
Also, I think you're right to have check on firstStart as the default.  I'll adjust above.

**Comment by lorensr** [comment]
I would say that's `reload: startAndResume` with a resume minimum 1 hr.

**Comment by jamielob** [comment]
But consider this situation.  `reload: 'start'` is set.  
- Code is downloaded while use the app.
- User multi-tasks away from the app for 5 minutes.
- Memory usage means the app is closed.
- User "resumes" the app.
- App is reloaded because it considers it a "start".

This is why I think we need a timer that says, if you come back to the app within a certain time, it should always be considered a resume.

This is based on the scenario provided here: https://github.com/jamielob/reloader/issues/3

**Comment by lorensr** [comment]
> App is reloaded because it considers it a "start".

We can't stop that from happening, right? With 1.3, if new code has been downloaded, it will be used on the next cold start?

**Comment by jamielob** [comment]
Hmmm. Yeh I think you're right, I'd forgotten that bit.  In that case I don't think there's a need for `resumeMethod` - I only introduced that to combat the above scenario.

**Comment by jamielob** [comment]
@lorensr You had previously mentioned two timers, one for check and one for resume - what scenario's were you thinking those would be used for?

**Comment by lorensr** [comment]
```
{
  check: 'firstStart'
  checkIdleCutoff: N/A
  checkTimer: 3000
  reload: 'startAndResume'
  reloadIdleCutoff: 1 hour? dunno. just don't want it restarting when the user is multitasking, and about to come back to the app soon.
  launchScreenDelay: 0
}
```

one for `reload startAndResume`, and one for `check: everyStart`

**Comment by adamgins** [comment]
@jamielob cool package - I have been hitting some issues with reload on resume (see https://github.com/meteor/meteor/issues/7876#issuecomment-260181121 ) and wanted to check if there's a config I could use for manual updates?

ie always be manual, use the `updateAvailable` helper to allow a user to manually get a hot code push.

**Comment by lorensr** [comment]
@adamgins yes you could do `check: false`, although I would at least do `'firstStart'`, and `refresh: 'start'` (default behavior in current Meteor)

**Comment by adamgins** [comment]
Hi @lorensr thanks, I am still seeing some refreshes on some users' phones without displaying the "click to reload". Always hard to debug on someone's physical phone, but I wanted to check two things regarding my configuration:

```
Reloader.configure({
    check: 'firstStart', // Check for new code every time the app starts
    checkTimer: 5000,  // Wait 3 seconds to see if new code is available
    refresh: 'start', 
    idleCutoff: 1000 * 60 * 10  // Wait 10 minutes before treating a resume as a start
});
```

So I am thinking of a couple of causes:

1) The user does not have the latest code... I had not refreshed the appStore yet, so `reloader` is not actually running

2) My settings allow a refresh

3) perhaps a bug

If I only want manual refreshes, ie via 

```
          {{#if updateAvailable}}
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <a class="button" reloader-update>Tap here to update the Buzzy app!</a>
                </div>

            {{/if}}
```

Are my settings correct or can the app refresh without a user clicking the button?

thanks for the help

**Comment by lorensr** [comment]
> Are my settings correct

Yep. And `idleCutoff` is unnecessary.

**Comment by jamielob** [comment]
@lorensr - closing the v2 issues since it looks like we've both moved on to React Native and probably won't improve this package.
