### ISSUE TITLE
Cannot read property 'configure' of undefined

### ISSUE THREAD

**Issue by qrobin** [jamielob/reloader#9]
Hello!

I tried to use your package, but seems like `Reloader` has no methods. What have I done wrong?

I just used basic configuration on client inside `main.js` file:

```
Reloader.configure({
    check: false,
    refresh: 'start'
})
```

![image](https://cloud.githubusercontent.com/assets/13153161/17646514/f6c7570c-61d5-11e6-8f00-eaedf864c235.png)

Also i tried to do:
- `import {Reloader} from "meteor/jamielob:reloader";`,
- place code inside `Meteor.startup()`.

Have not positive result.

**Comment by jamielob** [comment]
Hey @ababba15.  Import syntax is being worked on currently but isn't implemented.  Reloader should just be global for you.  So remove your import statement and you can tell your linter it's global using `/* global Reloader */`.

**Comment by lorensr** [comment]
Sorry @ababba15 – please call `Reloader.configure` only on the client, not the server (where it's undefined).
